### PR TITLE
Move from custom to off-the-shelf pre-commit

### LINKED ISSUE #82: Update documentation

### PR DESCRIPTION
**Pull request by 0atman**
RIP my automated dreams

ThriftyCalmKilldeer-size_restricted

### CODE REVIEW

**Review by emisaur — APPROVED** [review]
LGTM, only bit I'm not sure about is the `customise-pre-commit.py` file - it's not mentioned anywhere in the readme, so what are users meant to do with it?

**Comment by 0atman** [comment]
@emisaur thanks Em, that's a good point. That's a legacy from when we were going to do some customising. I'll remove it

**Review by emisaur — APPROVED** [review]
lgtm

**Review by danjoneslf — APPROVED** [review]
Is it worth adding something about what it doesn't detect well. So high entropy strings it will detect some but not others. So an HEC token it will detect sometimes but not reliably because it depends on the calculated entropy score for the specific string. Other client secret type things are likely similarly effected.

**Comment by 0atman** [comment]
@danjoneslf that's a good bit of documentation, I'll add in a "what works and what doesn't" section :ok_hand:

**Comment by 0atman** [comment]
@danjoneslf thanks for that! added that section, how does it look now?

**Comment by 0atman** [comment]
Cleaned up, this is ready :+1:

**Pull request merged**
